<?php
//styles generated by customizer
function directory_theme_customize_css()
{
	?>
	<style type="text/css">
		.container, .geodir-common, .geodir-breadcrumb, .geodir_full_page .widget {
			width:<?php echo get_theme_mod('css_container_width', CSS_CONTAINER_WIDTH); ?>;
			padding-right:<?php echo get_theme_mod('css_container_padding_right', CSS_CONTAINER_PADDING_RIGHT); ?>;
			padding-left:<?php echo get_theme_mod('css_container_padding_left', CSS_CONTAINER_PADDING_LEFT); ?>;
			margin-right:<?php echo get_theme_mod('css_container_margin_right', CSS_CONTAINER_MARGIN_RIGHT); ?>;
			margin-left:<?php echo get_theme_mod('css_container_margin_left', CSS_CONTAINER_MARGIN_LEFT); ?>;
		}
		.site-logo-wrap .site-logo {
			margin-right:<?php echo get_theme_mod('css_logo_margin_right', CSS_LOGO_MARGIN_RIGHT); ?>;
			margin-left:<?php echo get_theme_mod('css_logo_margin_left', CSS_LOGO_MARGIN_LEFT); ?>;
			margin-top:<?php echo get_theme_mod('css_logo_margin_top', CSS_LOGO_MARGIN_TOP); ?>;
			margin-bottom:<?php echo get_theme_mod('css_logo_margin_bottom', CSS_LOGO_MARGIN_BOTTOM); ?>;
		}
		body {
			/*font-family: font-family;*/
			font-size:<?php echo get_theme_mod('css_font_size', CSS_FONT_SIZE); ?>px;
			line-height:<?php echo get_theme_mod('css_line_height', CSS_LINE_HEIGHT); ?>px;
			background-color:<?php echo get_theme_mod('css_background_color', CSS_BACKGROUND_COLOR); ?>;
			color:<?php echo get_theme_mod('css_body_color', CSS_BODY_COLOR); ?>;
		}
		.content-box, .content .entry, #geodir_content, .sidebar .widget, .geodir-content-right .geodir-company_info, .geodir_full_page .geodir-category-list-in, .geodir_full_page .geodir-loc-bar {
			background-color: <?php echo get_theme_mod('css_content_bg', CSS_CONTENT_BG); ?>;
			border: 1px solid <?php echo get_theme_mod('css_content_border', CSS_CONTENT_BORDER); ?>;
			box-shadow: 0 1px 1px <?php echo get_theme_mod('css_content_shadow', CSS_CONTENT_SHADOW); ?>;
		}
		.alert-help {
			background-color:<?php echo get_theme_mod('css_alert_yellow', CSS_ALERT_YELLOW); ?>;
		}
		.alert-info {
			background-color:<?php echo get_theme_mod('css_alert_blue', CSS_ALERT_BLUE); ?>;
		}
		.alert-error{
			background-color:<?php echo get_theme_mod('css_alert_red', CSS_ALERT_RED); ?>;
		}
		.alert-success {
			background-color:<?php echo get_theme_mod('css_alert_green', CSS_ALERT_GREEN); ?>;
		}
		h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5 {
			color: <?php echo get_theme_mod('css_h1toh6_color', CSS_H1TOH6_COLOR); ?>;
		}
		a, a:visited {
			color: <?php echo get_theme_mod('css_link_color', CSS_LINK_COLOR); ?>;
		}
		a:hover,
		a:focus,
		a:active {
			color: <?php echo darken_color(get_theme_mod('css_link_color', CSS_LINK_COLOR), 9); ?>;
		}
		#primary-nav ul li {
			padding-right: <?php echo get_theme_mod('css_p_nav_padding_right', CSS_P_NAV_PADDING_RIGHT); ?>px;
		}
		#primary-nav ul li a {
			height: <?php echo get_theme_mod('css_p_nav_height', CSS_P_NAV_HEIGHT); ?>px;
			line-height: <?php echo get_theme_mod('css_p_nav_line_height', CSS_P_NAV_LINE_HEIGHT); ?>px;
		}
		button, input[type=button], input[type=reset], input[type=submit] {
			color:<?php echo get_theme_mod('css_btn_text_color', CSS_BTN_TEXT_COLOR); ?>;
			background-color:<?php echo get_theme_mod('css_btn_bg_color', CSS_BTN_BG_COLOR); ?>;
			border: 1px solid <?php echo get_theme_mod('css_btn_border_color', CSS_BTN_BORDER_COLOR); ?>;
		}
		button:hover, input[type=button]:hover, input[type=reset]:hover, input[type=submit]:hover {
			background-color:<?php echo darken_color(get_theme_mod('css_btn_bg_color', CSS_BTN_BG_COLOR), 9); ?>;
		}
		.footer-widgets {
			background-color: <?php echo get_theme_mod('css_footer_widget_bg', CSS_FOOTER_WIDGET_BG); ?>;
		}
		.copyright {
			background-color: <?php echo get_theme_mod('css_copyright_bg', CSS_COPYRIGHT_BG); ?>;
		}
		.copyright .container {
			padding-top: <?php echo get_theme_mod('css_copyright_padding_top', CSS_COPYRIGHT_PADDING_TOP); ?>px;
			padding-bottom: <?php echo get_theme_mod('css_copyright_padding_bottom', CSS_COPYRIGHT_PADDING_BOTTOM); ?>px;
		}
		.site-header {
			height: <?php echo get_theme_mod('css_header_height', CSS_HEADER_HEIGHT); ?>;px;
			background-color: <?php echo get_theme_mod('css_header_bg_color', CSS_HEADER_BG_COLOR); ?>;
		}
	</style>
	<?php
}
add_action( 'wp_head', 'directory_theme_customize_css');